baseurl: ""
url: "tiagodeoliveira.github.io" # the base hostname & protocol for your site.
title: "Tiago Oliveira"
description: "Solutions Architect, passionate about simple, elastic and reactive solutions!"

paginate: 10 #articles per page
paginate_path: /blog/page:num

#contacts
git: "https://github.com/tiagodeoliveira"
twitter: "https://twitter.com/_oliveira_tiago" 
email: "tiago@tiago.sh"
linkedin: "https://www.linkedin.com/in/tiagordeoliveira/"

disqus: 
  shortname: "tiagooliveira"

google: 
  tracking-id: "UA-117923824-1"

plugins:
  - jekyll-sitemap

# This is used by feed.xml. Uncomment if you want to use it.
# description: "..."

exclude:
  - "README.md"
  - "CHANGELOG.md"
  - "Gemfile"
  - "Gemfile.lock"
  - vendor
permalink: :title
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
